# Manifiesto de Argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tu-usuario/cicd-practica'
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
