# Circleci
version: 2.1
python: circleci/python@2.1.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.10.5

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      # Restaurar caché de dependencias de Python si existe
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      # Instalar dependencias
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8  
            
      # Ejecutar lint
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            flake8 .        

      # Guardar caché de dependencias
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

workflows:
  test-deploy:
    jobs:
      - test:
          context: dev
