# Circleci
version: 2.1
python: circleci/python@2.1.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.10.5

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0    

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      # Restaurar caché de dependencias de Python si existe
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      # Instalar dependencias
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r dev-requirements.txt 
            
      # Ejecutar lint
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            flake8 . 

      # Generar y guardar el archivo de cobertura             
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run -m pytest tests
            coverage xml -o coverage.xml

      - sonarcloud/scan

      # Guardar caché de dependencias
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # Almacenar coberura    
      - store_artifacts:
          path: coverage.xml
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - . 
  create_release:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Create GitHub Release
          command: |
            curl -u $GITHUB_USER:$GITHUB_TOKEN -X POST \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$GITHUB_USER/cicd-practica/releases \
              -d '{"tag_name":"v1.0.0","name":"Release v1.0.0","body":"feat: Añadir publicación en Github packages","draft":false,"prerelease":false}'             
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo        
      - run:
          name: Generate artifact
          command: |
            mkdir -p artifacts
            zip -r artifacts/app.zip .
      - store_artifacts:
          path: artifacts/app.zip
      - run:
          name: Publish to GitHub Packages
          command: |
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
            curl -u $GITHUB_USER:$GITHUB_TOKEN -T artifacts/app.zip https://uploads.github.com/repos/$GITHUB_USER/cicd-practica/releases/${RELEASE_ID}/assets?name=app-${CIRCLE_SHA1}.zip
         
workflows:
  test-deploy:
    jobs:
      - test:
          context: dev
      - create_release:
          context: dev
          requires:
            - test    
      - publish:
          context: dev
          requires:
            - test
          filters:
            branches:
              only:
                - main    
